name: "EPIC template"
description: "This template is intended for creating project epics."
title: "Example: [EPIC] Infrastructure; [EPIC] Backend; [EPIC] Frontend"
labels: []
assignees:
  -leafarRafael

body:
  type: textarea
  