name: "EPIC template"
description: "This template is intended for creating project epics"
title: "Ex: [EPIC] Infrastructure; [EPIC] Backend; [EPIC] Frontend"

assignees:
  - leafarRafael-Dev

body:
  - type: input
    id: epic-template
    attributes:
      label: "Short description"
      description: "Describe the objectives of this EPIC"
      placeholder: "Describe here"

  - type: textarea
    id: description
    attributes:
      label: "Detailed description"
      description: "Describe the elements that are part of this epic."
      placeholder: "Digite here"