name: "EPIC template"
description: "This template is intended for creating project epics"
title: "Ex: [EPIC] Infrastructure; [EPIC] Backend; [EPIC] Frontend"
labels: epic

assignees:
  - leafarRafael-Dev

body:
  - type: input
    id: epic-template
    attributes:
      label: "Short description"
      description: "Describe the objectives of this EPIC"
      placeholder: "Describe here"

  - type: textarea
    id: description
    attributes:
      label: "Detailed description"
      description: "Describe the elements that are part of this epic."
      placeholder: "Digite here"
    
  - type: checkboxes
    attributes:
      label: "Checklist personalizável"
      description: "Adicione seus próprios itens abaixo do exemplo"
      options:
        - label: "Exemplo: Item pré-definido (opcional)"
          required: false
  - type: textarea
    attributes:
      label: "Adicionar itens ao checklist"
      description: "Digite cada item em uma nova linha (serão convertidos em checkboxes)"
      placeholder: "- [ ] Item 1\n- [ ] Item 2\n- [ ] Item 3"
    validations:
      required: false