name: "EPIC template"
description: "This template is intended for creating project epics"
title: "Example: [EPIC] Infrastructure; [EPIC] Backend; [EPIC] Frontend"
assignees:
  -leafarRafael

body:
  type: textarea
  attributes:
    description: "Describe the objectives of this EPIC"